const arabic: Record<string, string> = {
  OpenAI: "أوبن إيه آي",
  openai: "أوبن إيه آي",
  Anthropic: "أنثروبيك",
  anthropic: "أنثروبيك",
  Google: "غوغل",
  Gemini: "جيميني",
  gemini: "غوغل جيميني",
  OpenRouter: "أوبن راوتر",
  openrouter: "أوبن راوتر",
  NVIDIA: "إنفيديا",
  nvidia: "إنفيديا",
  Meta: "ميتا",
  DeepSeek: "ديب سيك",
  Qwen: "كوين",
  Mistral: "ميسترال",
  SpaceXAI: "سبيس إكس إيه آي",
  Cohere: "كوهير",
  MoonshotAI: "مونشوت",
  MiniMax: "ميني ماكس",
  "Z.ai": "زد إيه آي",
  Microsoft: "مايكروسوفت",
  "GPT-6 Astra": "جي بي تي ٦ أسترا",
  "GPT-6 Sol": "جي بي تي ٦ سول",
  "GPT-6 Luna": "جي بي تي ٦ لونا",
  "Claude Opus 5.5": "كلود أوبوس ٥٫٥",
  "Claude Sonnet 5": "كلود سونيت ٥",
  "Claude Haiku 4.5": "كلود هايكو ٤٫٥",
  "Gemini 3.8 Flash": "جيميني ٣٫٨ فلاش",
  "Gemini 3.1 Pro Preview": "جيميني ٣٫١ برو — تجريبي",
  "Gemma 4 31B": "جيما ٤ — ٣١ مليارًا",
  "Llama 4 Maverick": "لاما ٤ مافريك",
  "Llama 4 Scout": "لاما ٤ سكاوت",
  "DeepSeek V4 Pro 0813": "ديب سيك ٤ برو ٠٨١٣",
  "DeepSeek V4.1 Flash": "ديب سيك ٤٫١ فلاش",
  R1: "آر ١",
  "Qwen3.8 Max Prime": "كوين ٣٫٨ ماكس برايم",
  "Qwen3.8 Flash": "كوين ٣٫٨ فلاش",
  "Qwen3 Coder Next": "كوين ٣ كودر نكست",
  "Mistral Large 3 2512": "ميسترال لارج ٣ — ٢٥١٢",
  "Mistral Small 4": "ميسترال سمول ٤",
  "Codestral 2508": "كودسترال ٢٥٠٨",
  "Grok 4.7": "غروك ٤٫٧",
  "Grok 4.6": "غروك ٤٫٦",
  "Command A+": "كوماند إيه بلس",
  "Command A": "كوماند إيه",
  "Kimi K3": "كيمي كيه ٣",
  "MiniMax M3": "ميني ماكس إم ٣",
  "GLM 5.3": "جي إل إم ٥٫٣",
  "Nemotron 3.5 Lightning": "نيموترون ٣٫٥ لايتنينغ",
  "Phi 4": "فاي ٤",
  "gpt-oss-120b": "جي بي تي المفتوح — ١٢٠ مليارًا",
  Atlas: "أطلس",
  Swift: "سويفت",
  Prism: "بريزم",
};
export function displayName(value: string, locale: string) {
  return locale === "ar" ? (arabic[value] ?? value) : value;
}

export const ARABIC_LANGUAGES: Record<string, string> = {
  ar: "العربية",
  en: "الإنجليزية",
  fr: "الفرنسية",
  es: "الإسبانية",
  zh: "الصينية",
  ko: "الكورية",
  ur: "الأردية",
  fa: "الفارسية",
  pt: "البرتغالية",
  it: "الإيطالية",
  ru: "الروسية",
  de: "الألمانية",
  nl: "الهولندية",
};
